name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Déclenche le workflow sur un push vers la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Utilisez la version Python que vous utilisez dans votre projet

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assurez-vous que votre fichier requirements.txt est dans le repo

      - name: Deploy to Heroku
        uses: akshnz/heroku-deploy@v1
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}  # Définissez cette clé dans vos secrets GitHub
          heroku_app_name: "your-heroku-app-name"  # Remplacez par le nom de votre app Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}  # Définissez cette variable d'email dans vos secrets GitHub
